RAMPART_PORT_1: 1100
RAMPART_PORT_2: 1200
ARCHIVED_RUNS: 'archived_runs'
RUNS_DIR: 'runs'
SHOW_RAMPART: true
RAMPART_IMAGE: 'coreyansley/artifice_polio_rampart'
RAMPART_LOGFILE: 'RAMPART_log.txt'
PIRANHA_IMAGE: 'polionanopore/piranha'
PIRANHA_LOGFILE: 'PIRANHA_log.txt'
LOGFILE: 'log.txt'
THREADS: null
FIRST_TIME_SETUP: true
LANGUAGE: 'English'
VERSION: 'piranhaGUI'
SCALING: 1
VALUE_POSITIVE: 'positive'
VALUE_NEGATIVE: 'negative'
VALUE_SAMPLE_TYPE: 'stool'
VALUE_MIN_MAP_QUALITY: 50
VALUE_MIN_READ_LENGTH: 1000
VALUE_MAX_READ_LENGTH: 1300
VALUE_MIN_READS: 50
VALUE_MIN_PCENT: 10
VALUE_PRIMER_LENGTH: 30
VALUE_OUTPUT_PREFIX: "analysis"
PHYLO_ENABLED: false
PHYLO_DIR: ""
