name: artifice
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=21.2.4
  - pip:
    - Pillow==9.0.1
    - PySimpleGUI==4.60.3 #4.55.1
    - docker==6.1.2
    - requests==2.27.1
    - pyyaml==6.0
    - py2app==0.28.4 #0.26.1
    - pyinstaller==5.0.1
